# config.yaml

model:
  type: gpt2
  vocab_size: 50257
  n_layers: 12
  n_heads: 12
  hidden_size: 768
  max_position_embeddings: 1024
  dropout: 0.1
  initializer_range: 0.02

tokenizer:
  type: custom
  vocab_file: "data/tokenizer/vocab.json"
  merges_file: "data/tokenizer/merges.txt"
  pad_token: "<|pad|>"
  eos_token: ""

training:
  batch_size: 8
  micro_batch_size: 1
  epochs: 10
  learning_rate: 0.0006
  weight_decay: 0.01
  warmup_steps: 1000
  gradient_accumulation_steps: 8
  lr_scheduler: cosine
  max_grad_norm: 1.0
  log_interval: 10
  save_interval: 1000
  eval_interval: 1000
  checkpoint_dir: "checkpoints"

data:
  train_path: "data/train.txt"
  val_path: "data/val.txt"
  block_size: 1024
  num_workers: 2

device:
  type: cuda
  use_amp: true  # automatic mixed precision

logging:
  use_wandb: false
  wandb_project: "joey-llm"
  output_dir: "logs"

seed: 42

