name: 🐛 JoeyLLM Bug Report
description: Report a bug in JoeyLLM development
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve JoeyLLM! Please complete the following form.

  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: "Brief description of the bug"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the stack is this about?
      options:
        - model
        - training
        - config
        - data
        - tokenizer
        - evaluation
        - inference
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue in detail and how to reproduce it.
      placeholder: |
        1. Run training with config xyz.yaml
        2. Observe error or crash
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Tracebacks (if any)
      description: Paste any logs or error messages here.
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low (minor issue, workaround exists)
        - Medium (affects function, limited workaround)
        - High (blocks work or training completely)
    validations:
      required: true
