name: Model Architecture Update
description: Propose or document a change to the model's architecture
title: "[ARCH] <short description of change>"
labels: [architecture, model]
body:
  - type: input
    id: component
    attributes:
      label: Target Component
      description: Which part of the model is being updated?
      placeholder: e.g., Attention block, Positional embedding, Output head
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change being proposed? What problem does it solve?
      placeholder: e.g., Improve training efficiency or adapt to new data type
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Proposed Change
      description: Describe the architecture change in detail.
      placeholder: e.g., Replace absolute positional embeddings with rotary embeddings
    validations:
      required: true

  - type: textarea
    id: expected-impact
    attributes:
      label: Expected Impact
      placeholder: e.g., Improved convergence, reduced memory usage
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Implementation Checklist
      options:
        - label: Code updated in `joeyllm.py`
        - label: Unit tests updated
        - label: Docs or comments updated
