model:
  type: "Joeyllm"
  vocab_size: 50257
  max_seq_len: 64
  embed_dim: 768
  num_heads: 8
  num_layers: 4
  dropout: 0.1
  batch_size: 4
  device: "auto"

data:
  dataset_out: "SouthernCrossAI/Gutenberg-Australia-Chunks-512"
  dataset_in: "SouthernCrossAI/Gutenberg-Australia-Chunks-512"
  batch_size: 8
  columns: ["input_ids"]
  format: "torch"
  shuffle: true
  use_validation: true
  use_test: true
