name: Auto-Add Bugs to Bug Tracker Project

on:
  issues:
    types: [opened, labeled]

jobs:
  add-bug-to-project:
    if: contains(github.event.issue.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub Project (Bug Tracker)
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: https://github.com/orgs/southern-cross-ai/projects/58
          column_name: To triage
        env:
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


